//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace imranvize.Models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenci
    {
        public int ogrenciid { get; set; }
        public string ogrenciad { get; set; }
        public string ogrencisoyad { get; set; }
        public Nullable<int> ogrencikredi { get; set; }
        public Nullable<System.DateTime> ogrencigiris { get; set; }
        public Nullable<System.DateTime> ogrencicıkıs { get; set; }
    }
}
